const LANGS={
 ar:{name:'العربية',dir:'rtl',tag:'أوقات الصلاة لكل مدينة في العالم، تُحدّث يوميًا.',nothing:'أوقات الصلاة فقط.',choose:'اختر مدينة',search:'ابحث عن أي مدينة في العالم...',searchBtn:'بحث',location:'استخدم موقعي',next:'الصلاة القادمة',monthly:'الشهر',qibla:'القبلة',monthlyTitle:'أوقات الصلاة الشهرية',qiblaTitle:'القبلة',qiblaDesc:'اتجاه القبلة من مدينتك المختارة.',enable:'تفعيل البوصلة',fajr:'الفجر',sunrise:'الشروق',dhuhr:'الظهر',asr:'العصر',maghrib:'المغرب',isha:'العشاء',loading:'جارٍ التحميل…',error:'تعذر تحميل البيانات. حاول مرة أخرى.'},
 en:{name:'English',dir:'ltr',tag:'Prayer times for every city in the world, updated daily.',nothing:'Prayer times. Nothing more.',choose:'Choose a city',search:'Search any city in the world...',searchBtn:'Search',location:'Use my location',next:'NEXT PRAYER',monthly:'Monthly',qibla:'Qibla',monthlyTitle:'Monthly prayer times',qiblaTitle:'Qibla',qiblaDesc:'Direction to the Kaaba from your selected city.',enable:'Enable compass',fajr:'Fajr',sunrise:'Sunrise',dhuhr:'Dhuhr',asr:'Asr',maghrib:'Maghrib',isha:'Isha',loading:'Loading…',error:'Could not load data. Please try again.'},
 fr:{name:'Français',dir:'ltr',tag:'Horaires de prière pour chaque ville du monde, mis à jour quotidiennement.',nothing:'Horaires de prière. Rien de plus.',choose:'Choisir une ville',search:'Rechercher une ville dans le monde...',searchBtn:'Rechercher',location:'Utiliser ma position',next:'PROCHAINE PRIÈRE',monthly:'Mois',qibla:'Qibla',monthlyTitle:'Horaires mensuels',qiblaTitle:'Qibla',qiblaDesc:'Direction de la Kaaba depuis votre ville.',enable:'Activer la boussole',fajr:'Fajr',sunrise:'Lever du soleil',dhuhr:'Dhuhr',asr:'Asr',maghrib:'Maghrib',isha:'Isha',loading:'Chargement…',error:'Impossible de charger les données.'},
 es:{name:'Español',dir:'ltr',tag:'Horarios de oración para todas las ciudades del mundo, actualizados a diario.',nothing:'Horarios de oración. Nada más.',choose:'Elegir ciudad',search:'Buscar cualquier ciudad del mundo...',searchBtn:'Buscar',location:'Usar mi ubicación',next:'PRÓXIMA ORACIÓN',monthly:'Mensual',qibla:'Qibla',monthlyTitle:'Horarios mensuales',qiblaTitle:'Qibla',qiblaDesc:'Dirección de la Kaaba desde tu ciudad.',enable:'Activar brújula',fajr:'Fajr',sunrise:'Amanecer',dhuhr:'Dhuhr',asr:'Asr',maghrib:'Maghrib',isha:'Isha',loading:'Cargando…',error:'No se pudieron cargar los datos.'},
 zh:{name:'中文',dir:'ltr',tag:'世界各地城市的每日礼拜时间，每天更新。',nothing:'礼拜时间，仅此而已。',choose:'选择城市',search:'搜索世界上的城市...',searchBtn:'搜索',location:'使用我的位置',next:'下一次礼拜',monthly:'月历',qibla:'朝向',monthlyTitle:'每月礼拜时间',qiblaTitle:'朝向',qiblaDesc:'从所选城市前往天房的方向。',enable:'启用指南针',fajr:'晨礼',sunrise:'日出',dhuhr:'晌礼',asr:'晡礼',maghrib:'昏礼',isha:'宵礼',loading:'加载中…',error:'无法加载数据。'},
 hi:{name:'हिन्दी',dir:'ltr',tag:'दुनिया के हर शहर के लिए नमाज़ के समय, रोज़ अपडेट।',nothing:'नमाज़ के समय। बस इतना ही।',choose:'शहर चुनें',search:'दुनिया में कोई भी शहर खोजें...',searchBtn:'खोजें',location:'मेरी लोकेशन इस्तेमाल करें',next:'अगली नमाज़',monthly:'मासिक',qibla:'क़िबला',monthlyTitle:'मासिक नमाज़ समय',qiblaTitle:'क़िबला',qiblaDesc:'आपके चुने शहर से काबा की दिशा।',enable:'कम्पास सक्षम करें',fajr:'फ़ज्र',sunrise:'सूर्योदय',dhuhr:'ज़ुहर',asr:'अस्र',maghrib:'मग़रिब',isha:'ईशा',loading:'लोड हो रहा है…',error:'डेटा लोड नहीं हो सका।'},
 ru:{name:'Русский',dir:'ltr',tag:'Время молитв для каждого города мира, обновляется ежедневно.',nothing:'Время молитв. Ничего лишнего.',choose:'Выберите город',search:'Найти любой город мира...',searchBtn:'Поиск',location:'Использовать моё местоположение',next:'СЛЕДУЮЩАЯ МОЛИТВА',monthly:'Месяц',qibla:'Кибла',monthlyTitle:'Время молитв на месяц',qiblaTitle:'Кибла',qiblaDesc:'Направление к Каабе из выбранного города.',enable:'Включить компас',fajr:'Фаджр',sunrise:'Восход',dhuhr:'Зухр',asr:'Аср',maghrib:'Магриб',isha:'Иша',loading:'Загрузка…',error:'Не удалось загрузить данные.'},
 fa:{name:'فارسی',dir:'rtl',tag:'اوقات نماز برای همه شهرهای جهان، هر روز به‌روزرسانی می‌شود.',nothing:'اوقات نماز. همین.',choose:'انتخاب شهر',search:'جستجوی هر شهر در جهان...',searchBtn:'جستجو',location:'استفاده از موقعیت من',next:'نماز بعدی',monthly:'ماهانه',qibla:'قبله',monthlyTitle:'اوقات نماز ماهانه',qiblaTitle:'قبله',qiblaDesc:'جهت کعبه از شهر انتخابی شما.',enable:'فعال‌کردن قطب‌نما',fajr:'صبح',sunrise:'طلوع',dhuhr:'ظهر',asr:'عصر',maghrib:'مغرب',isha:'عشاء',loading:'در حال بارگذاری…',error:'بارگذاری اطلاعات ناموفق بود.'}
};
const prayerKeys=['fajr','sunrise','dhuhr','asr','maghrib','isha'];
const apiLang={ar:'ar',en:'en',fr:'fr',es:'es',zh:'en',hi:'en',ru:'en',fa:'fa'};
let lang=localStorage.getItem('salat_lang')||''; let city=JSON.parse(localStorage.getItem('salat_city')||'null'); let times=null; let timer=null; let qibla=0;
const $=id=>document.getElementById(id);
function t(k){return LANGS[lang]?.[k]||LANGS.en[k]||k}
function renderLangs(){ $('language-grid').innerHTML=Object.entries(LANGS).map(([k,v])=>`<button class="language-option" data-lang="${k}">${v.name}</button>`).join(''); document.querySelectorAll('.language-option').forEach(b=>b.onclick=()=>chooseLang(b.dataset.lang)); }
function chooseLang(k){lang=k;localStorage.setItem('salat_lang',k);applyLang();$('language-screen').classList.add('hidden');$('app').classList.remove('hidden');if(city)loadCity(city);}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=LANGS[lang].dir;$('language-subtitle').textContent=t('tag');$('tagline').textContent=t('nothing');$('city-label').textContent=city?`${city.name}, ${city.country}`:t('choose');$('city-search').placeholder=t('search');$('search-button').textContent=t('searchBtn');$('location-button').textContent=`◎ ${t('location')}`;$('next-label').textContent=t('next');$('monthly-button').querySelector('span').textContent=t('monthly');$('qibla-button').querySelector('span').textContent=t('qibla');$('monthly-title').textContent=t('monthlyTitle');$('qibla-title').textContent=t('qiblaTitle');$('qibla-description').textContent=t('qiblaDesc');$('orientation-button').textContent=t('enable');$('language-button').textContent=LANGS[lang].name;}
async function searchCities(){const q=$('city-search').value.trim();if(q.length<2){$('search-results').innerHTML='';return} try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=7&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});const data=await r.json();$('search-results').innerHTML=data.map(x=>`<button class="result" data-lat="${x.lat}" data-lon="${x.lon}" data-name="${escapeHtml(x.display_name.split(',')[0])}" data-country="${escapeHtml(x.address?.country||'')}" data-tz="">${escapeHtml(x.display_name.split(',').slice(0,2).join(', '))}<small>${escapeHtml(x.display_name)}</small></button>`).join('');document.querySelectorAll('.result').forEach(b=>b.onclick=()=>loadCity({name:b.dataset.name,country:b.dataset.country,lat:+b.dataset.lat,lon:+b.dataset.lon}));}catch(e){$('status').textContent=t('error')}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function reverseGeocode(lat,lon){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}&zoom=10`);const x=await r.json();return {name:x.address?.city||x.address?.town||x.address?.village||x.address?.municipality||'My location',country:x.address?.country||'',lat,lon}}catch{return {name:'My location',country:'',lat,lon}}}
async function loadCity(c){city=c;localStorage.setItem('salat_city',JSON.stringify(city));$('search-results').innerHTML='';$('city-search').value='';$('city-label').textContent=`${city.name}${city.country?', '+city.country:''}`;$('city-name').textContent=`${city.name}${city.country?', '+city.country:''}`;$('prayer-content').classList.remove('hidden');$('status').textContent='';await loadToday();}
async function loadToday(){try{const date=new Date();const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');const url=`https://api.aladhan.com/v1/timings/${d}-${m}-${y}?latitude=${city.lat}&longitude=${city.lon}&method=3`;const r=await fetch(url);const j=await r.json();if(j.code!==200)throw Error();times=j.data.timings;renderDate(j.data.date);renderTimes();}catch(e){$('status').textContent=t('error')}}
function renderDate(d){$('gregorian-date').textContent=d.gregorian?.weekday?.en?`${d.gregorian.weekday.en}, ${d.gregorian.date}`:new Date().toLocaleDateString();$('hijri-date').textContent=d.hijri?.date?`${d.hijri.date} ${d.hijri.month?.en||''} ${d.hijri.year}`:''}
function parseTime(v){const [h,m]=v.split(':').map(Number);return h*60+m}
function renderTimes(){const now=new Date();const mins=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;let next=-1;for(let i=0;i<prayerKeys.length;i++){if(prayerKeys[i]==='sunrise')continue;if(parseTime(times[prayerKeys[i]])>mins){next=i;break}}if(next<0)next=0;$('next-prayer').textContent=t(prayerKeys[next]);$('next-time').textContent=times[prayerKeys[next]];$('prayer-list').innerHTML=prayerKeys.map((k,i)=>`<div class="prayer-row ${i===next?'next':''}"><strong>${t(k)}</strong><time>${times[k]}</time></div>`).join('');startCountdown(next);}
function startCountdown(next){clearInterval(timer);const tick=()=>{if(!times)return;const now=new Date();let target=new Date(now);const key=prayerKeys[next];const [h,m]=times[key].split(':').map(Number);target.setHours(h,m,0,0);if(target<=now)target.setDate(target.getDate()+1);let s=Math.max(0,Math.floor((target-now)/1000));const hh=String(Math.floor(s/3600)).padStart(2,'0');s%=3600;const mm=String(Math.floor(s/60)).padStart(2,'0');const ss=String(s%60).padStart(2,'0');$('countdown').textContent=`${hh}:${mm}:${ss}`};tick();timer=setInterval(tick,1000)}
async function monthly(){if(!city)return;$('monthly-panel').classList.remove('hidden');$('monthly-loading').classList.remove('hidden');$('monthly-body').innerHTML='';const d=new Date();try{const r=await fetch(`https://api.aladhan.com/v1/calendar/${d.getFullYear()}/${d.getMonth()+1}?latitude=${city.lat}&longitude=${city.lon}&method=3`);const j=await r.json();$('monthly-loading').classList.add('hidden');$('monthly-head').innerHTML=`<th>Date</th>${prayerKeys.map(k=>`<th>${t(k)}</th>`).join('')}`;$('monthly-body').innerHTML=j.data.map(x=>`<tr><td>${x.date.gregorian.day}</td>${prayerKeys.map(k=>`<td>${x.timings[k]}</td>`).join('')}</tr>`).join('')}catch{$('monthly-loading').textContent=t('error')}}
function calculateQibla(lat,lon){const kaabaLat=21.422487,kaabaLon=39.826206;const p1=lat*Math.PI/180,p2=kaabaLat*Math.PI/180,dl=(kaabaLon-lon)*Math.PI/180;const y=Math.sin(dl)*Math.cos(p2);const x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return (Math.atan2(y,x)*180/Math.PI+360)%360}
function showQibla(){if(!city)return;$('qibla-panel').classList.remove('hidden');qibla=calculateQibla(city.lat,city.lon);$('qibla-bearing').textContent=`${Math.round(qibla)}°`;rotateCompass(qibla)}
function rotateCompass(v){$('compass-arrow').style.transform=`rotate(${v}deg)`}
async function enableOrientation(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')return}window.addEventListener('deviceorientation',e=>{if(typeof e.alpha==='number')rotateCompass(qibla-e.alpha)});}catch{}}
$('city-search').addEventListener('input',searchCities);$('search-button').onclick=searchCities;$('location-button').onclick=async()=>{if(!navigator.geolocation)return $('status').textContent=t('error');navigator.geolocation.getCurrentPosition(async p=>loadCity(await reverseGeocode(p.coords.latitude,p.coords.longitude)),()=>$('status').textContent=t('error'))};$('monthly-button').onclick=monthly;$('qibla-button').onclick=showQibla;$('orientation-button').onclick=enableOrientation;$('language-button').onclick=()=>{ $('language-screen').classList.remove('hidden');$('app').classList.add('hidden')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));$('year').textContent=new Date().getFullYear();renderLangs();if(lang){applyLang();$('language-screen').classList.add('hidden');$('app').classList.remove('hidden');if(city)loadCity(city)}
