const LANGS={
 ar:{name:'العربية',dir:'rtl',tag:'أوقات الصلاة لكل مدينة في العالم، تُحدّث يوميًا.',nothing:'أوقات الصلاة فقط.',choose:'اختر مدينة',search:'ابحث عن أي مدينة في العالم...',searchBtn:'بحث',location:'استخدم موقعي',next:'الصلاة القادمة',today:'اليوم',tomorrow:'غدًا',monthly:'الشهر',qibla:'القبلة',monthlyTitle:'أوقات الصلاة الشهرية',qiblaTitle:'القبلة',qiblaDesc:'اتجاه القبلة من مدينتك المختارة.',enable:'تفعيل البوصلة',loading:'جارٍ التحميل…',error:'تعذر تحميل البيانات. حاول مرة أخرى.',timezone:'المنطقة الزمنية'},
 en:{name:'English',dir:'ltr',tag:'Prayer times for every city in the world, updated daily.',nothing:'Prayer times. Nothing more.',choose:'Choose a city',search:'Search any city in the world...',searchBtn:'Search',location:'Use my location',next:'NEXT PRAYER',today:'Today',tomorrow:'Tomorrow',monthly:'Monthly',qibla:'Qibla',monthlyTitle:'Monthly prayer times',qiblaTitle:'Qibla',qiblaDesc:'Direction to the Kaaba from your selected city.',enable:'Enable compass',loading:'Loading…',error:'Could not load data. Please try again.',timezone:'Time zone'},
 fr:{name:'Français',dir:'ltr',tag:'Horaires de prière pour chaque ville du monde, mis à jour quotidiennement.',nothing:'Horaires de prière. Rien de plus.',choose:'Choisir une ville',search:'Rechercher une ville dans le monde...',searchBtn:'Rechercher',location:'Utiliser ma position',next:'PROCHAINE PRIÈRE',today:"Aujourd’hui",tomorrow:'Demain',monthly:'Mois',qibla:'Qibla',monthlyTitle:'Horaires mensuels',qiblaTitle:'Qibla',qiblaDesc:'Direction de la Kaaba depuis votre ville.',enable:'Activer la boussole',loading:'Chargement…',error:'Impossible de charger les données.',timezone:'Fuseau horaire'},
 es:{name:'Español',dir:'ltr',tag:'Horarios de oración para todas las ciudades del mundo, actualizados a diario.',nothing:'Horarios de oración. Nada más.',choose:'Elegir ciudad',search:'Buscar cualquier ciudad del mundo...',searchBtn:'Buscar',location:'Usar mi ubicación',next:'PRÓXIMA ORACIÓN',today:'Hoy',tomorrow:'Mañana',monthly:'Mensual',qibla:'Qibla',monthlyTitle:'Horarios mensuales',qiblaTitle:'Qibla',qiblaDesc:'Dirección de la Kaaba desde tu ciudad.',enable:'Activar brújula',loading:'Cargando…',error:'No se pudieron cargar los datos.',timezone:'Zona horaria'},
 zh:{name:'中文',dir:'ltr',tag:'世界各地城市的每日礼拜时间，每天更新。',nothing:'礼拜时间，仅此而已。',choose:'选择城市',search:'搜索世界上的城市...',searchBtn:'搜索',location:'使用我的位置',next:'下一次礼拜',today:'今天',tomorrow:'明天',monthly:'月历',qibla:'朝向',monthlyTitle:'每月礼拜时间',qiblaTitle:'朝向',qiblaDesc:'从所选城市前往天房的方向。',enable:'启用指南针',loading:'加载中…',error:'无法加载数据。',timezone:'时区'},
 hi:{name:'हिन्दी',dir:'ltr',tag:'दुनिया के हर शहर के लिए नमाज़ के समय, रोज़ अपडेट।',nothing:'नमाज़ के समय। बस इतना ही।',choose:'शहर चुनें',search:'दुनिया में कोई भी शहर खोजें...',searchBtn:'खोजें',location:'मेरी लोकेशन इस्तेमाल करें',next:'अगली नमाज़',today:'आज',tomorrow:'कल',monthly:'मासिक',qibla:'क़िबला',monthlyTitle:'मासिक नमाज़ समय',qiblaTitle:'क़िबला',qiblaDesc:'आपके चुने शहर से काबा की दिशा।',enable:'कम्पास सक्षम करें',loading:'लोड हो रहा है…',error:'डेटा लोड नहीं हो सका।',timezone:'समय क्षेत्र'},
 ru:{name:'Русский',dir:'ltr',tag:'Время молитв для каждого города мира, обновляется ежедневно.',nothing:'Время молитв. Ничего лишнего.',choose:'Выберите город',search:'Найти любой город мира...',searchBtn:'Поиск',location:'Использовать моё местоположение',next:'СЛЕДУЮЩАЯ МОЛИТВА',today:'Сегодня',tomorrow:'Завтра',monthly:'Месяц',qibla:'Кибла',monthlyTitle:'Время молитв на месяц',qiblaTitle:'Кибла',qiblaDesc:'Направление к Каабе из выбранного города.',enable:'Включить компас',loading:'Загрузка…',error:'Не удалось загрузить данные.',timezone:'Часовой пояс'},
 fa:{name:'فارسی',dir:'rtl',tag:'اوقات نماز برای همه شهرهای جهان، هر روز به‌روزرسانی می‌شود.',nothing:'اوقات نماز. همین.',choose:'انتخاب شهر',search:'جستجوی هر شهر در جهان...',searchBtn:'جستجو',location:'استفاده از موقعیت من',next:'نماز بعدی',today:'امروز',tomorrow:'فردا',monthly:'ماهانه',qibla:'قبله',monthlyTitle:'اوقات نماز ماهانه',qiblaTitle:'قبله',qiblaDesc:'جهت کعبه از شهر انتخابی شما.',enable:'فعال‌کردن قطب‌نما',loading:'در حال بارگذاری…',error:'بارگذاری اطلاعات ناموفق بود.',timezone:'منطقه زمانی'}
};
const prayerKeys=['fajr','sunrise','dhuhr','asr','maghrib','isha'];
const apiNames={fajr:'Fajr',sunrise:'Sunrise',dhuhr:'Dhuhr',asr:'Asr',maghrib:'Maghrib',isha:'Isha'};
const countryMethods={dz:19,sa:4,eg:5,ma:21,tn:18,tr:13,ru:14,pk:1,in:1,bd:1,gb:3,fr:12,us:2,ca:2,id:20,my:17,sg:11,qa:10,kw:9,ae:8,jo:23,ir:7};
let lang=localStorage.getItem('salat_lang')||'';
let city=JSON.parse(localStorage.getItem('salat_city')||'null');
let days={today:null,tomorrow:null};
let selectedDay='today'; let timer=null; let qibla=0;
const $=id=>document.getElementById(id);
function t(k){return LANGS[lang]?.[k]||LANGS.en[k]||k}
function methodForCity(){return countryMethods[(city?.countryCode||'').toLowerCase()]||3}
function cacheKey(date){return `salat_times_v2_${city.lat.toFixed(4)}_${city.lon.toFixed(4)}_${date}_${methodForCity()}`}
function formatDateParts(offsetDays=0){const d=new Date();d.setDate(d.getDate()+offsetDays);return `${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${d.getFullYear()}`}
function renderLangs(){ $('language-grid').innerHTML=Object.entries(LANGS).map(([k,v])=>`<button class="language-option" data-lang="${k}">${v.name}</button>`).join('');document.querySelectorAll('.language-option').forEach(b=>b.onclick=()=>chooseLang(b.dataset.lang)); }
function chooseLang(k){lang=k;localStorage.setItem('salat_lang',k);applyLang();$('language-screen').classList.add('hidden');$('app').classList.remove('hidden');if(city)loadCity(city);}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=LANGS[lang].dir;$('language-subtitle').textContent=t('tag');$('tagline').textContent=t('nothing');$('city-label').textContent=city?`${city.name}${city.country?', '+city.country:''}`:t('choose');$('city-search').placeholder=t('search');$('search-button').textContent=t('searchBtn');$('location-button').textContent=`◎ ${t('location')}`;$('next-label').textContent=t('next');$('today-tab').textContent=t('today');$('tomorrow-tab').textContent=t('tomorrow');$('monthly-button').querySelector('span').textContent=t('monthly');$('qibla-button').querySelector('span').textContent=t('qibla');$('monthly-title').textContent=t('monthlyTitle');$('qibla-title').textContent=t('qiblaTitle');$('qibla-description').textContent=t('qiblaDesc');$('orientation-button').textContent=t('enable');$('language-button').textContent=LANGS[lang].name;}
function searchCities(){clearTimeout(searchCities._timer);const q=$('city-search').value.trim();if(q.length<2){$('search-results').innerHTML='';return}searchCities._timer=setTimeout(async()=>{try{const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&namedetails=1&featureType=settlement&layer=address&limit=10&dedupe=1&q=${encodeURIComponent(q)}&accept-language=${encodeURIComponent(lang||'en')}`;const r=await fetch(url);const data=await r.json();$('search-results').innerHTML=data.map(x=>{const name=x.address?.city||x.address?.town||x.address?.village||x.address?.municipality||x.display_name.split(',')[0];return `<button class="result" data-lat="${x.lat}" data-lon="${x.lon}" data-name="${escapeHtml(name)}" data-country="${escapeHtml(x.address?.country||'')}" data-code="${escapeHtml(x.address?.country_code||'')}">${escapeHtml(name)}, ${escapeHtml(x.address?.country||'')}<small>${escapeHtml(x.display_name)}</small></button>`}).join('');document.querySelectorAll('.result').forEach(b=>b.onclick=()=>loadCity({name:b.dataset.name,country:b.dataset.country,countryCode:b.dataset.code,lat:+b.dataset.lat,lon:+b.dataset.lon}));}catch(e){$('status').textContent=t('error')}},300)}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function reverseGeocode(lat,lon){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&lat=${lat}&lon=${lon}&zoom=10&accept-language=${encodeURIComponent(lang||'en')}`);const x=await r.json();return {name:x.address?.city||x.address?.town||x.address?.village||x.address?.municipality||'My location',country:x.address?.country||'',countryCode:x.address?.country_code||'',lat,lon}}catch{return {name:'My location',country:'',countryCode:'',lat,lon}}}
async function loadCity(c){city=c;localStorage.setItem('salat_city',JSON.stringify(city));$('search-results').innerHTML='';$('city-search').value='';$('city-label').textContent=`${city.name}${city.country?', '+city.country:''}`;$('city-name').textContent=`${city.name}${city.country?', '+city.country:''}`;$('prayer-content').classList.remove('hidden');$('status').textContent='';selectedDay='today';setActiveTab();await loadBothDays();}
async function fetchDay(offset){const date=formatDateParts(offset),key=cacheKey(date),cached=localStorage.getItem(key);if(cached){try{const obj=JSON.parse(cached);if(obj&&obj.data)return obj.data}catch{}}const url=`https://api.aladhan.com/v1/timings/${date}?latitude=${encodeURIComponent(city.lat)}&longitude=${encodeURIComponent(city.lon)}&method=${methodForCity()}&iso8601=true&latitudeAdjustmentMethod=3`;const r=await fetch(url);const j=await r.json();if(j.code!==200)throw Error('API');const data=j.data;localStorage.setItem(key,JSON.stringify({savedAt:Date.now(),data}));return data}
async function loadBothDays(){try{const [today,tomorrow]=await Promise.all([fetchDay(0),fetchDay(1)]);days={today,tomorrow};$('timezone').textContent=`${t('timezone')}: ${today.meta?.timezone||'—'}`;renderSelectedDay();}catch(e){$('status').textContent=t('error')}}
function setActiveTab(){document.querySelectorAll('.day-tab').forEach(b=>b.classList.remove('active'));$(selectedDay==='today'?'today-tab':'tomorrow-tab').classList.add('active')}
function renderSelectedDay(){setActiveTab();const data=days[selectedDay];if(!data)return;renderDate(data.date);renderPrayerList(data);}
function renderDate(d){const g=d.gregorian,h=d.hijri;$('gregorian-date').textContent=g?.weekday?.en?`${g.weekday.en}, ${g.date}`:g?.date||'';$('hijri-date').textContent=h?.date?`${h.date} ${h.month?.en||''} ${h.year}`:''}
function parseMinutes(v){const [h,m]=String(v).split(':').map(Number);return h*60+m}
function renderPrayerList(data){const now=new Date();const localNow=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;let next=-1;if(selectedDay==='today'){for(let i=0;i<prayerKeys.length;i++){if(prayerKeys[i]==='sunrise')continue;if(parseMinutes(data.timings[apiNames[prayerKeys[i]]])>localNow){next=i;break}}}if(next<0&&selectedDay==='today')next=0;const first=prayerKeys.findIndex(k=>k==='fajr');$('next-prayer').textContent=t(selectedDay==='tomorrow'?'fajr':(prayerKeys[next]||'fajr'));$('next-time').textContent=data.timings[apiNames[selectedDay==='tomorrow'?'fajr':(prayerKeys[next]||'fajr')]];$('countdown').textContent=selectedDay==='tomorrow'?'—': '00:00:00';$('prayer-list').innerHTML=prayerKeys.map((k,i)=>`<div class="prayer-row ${i===next?'next':''}"><strong>${t(k)}</strong><time>${data.timings[apiNames[k]]}</time></div>`).join('');if(selectedDay==='today')startCountdown(data,next);else clearInterval(timer)}
function startCountdown(data,next){clearInterval(timer);const tick=()=>{const key=apiNames[prayerKeys[next]||'fajr'];const iso=data.timings[key]?.split(' ')[0];const offsetIso=data.timings[key];let target=offsetIso?new Date(offsetIso):null;if(!target||Number.isNaN(target.getTime())){const [h,m]=String(data.timings[key]).split(':').map(Number);target=new Date();target.setHours(h,m,0,0)}const now=new Date();if(target<=now){target=new Date(target.getTime()+86400000)}let s=Math.max(0,Math.floor((target-now)/1000));const hh=String(Math.floor(s/3600)).padStart(2,'0');s%=3600;const mm=String(Math.floor(s/60)).padStart(2,'0');const ss=String(s%60).padStart(2,'0');$('countdown').textContent=`${hh}:${mm}:${ss}`};tick();timer=setInterval(tick,1000)}
async function monthly(){if(!city)return;$('monthly-panel').classList.remove('hidden');$('monthly-loading').classList.remove('hidden');$('monthly-body').innerHTML='';const d=new Date();try{const r=await fetch(`https://api.aladhan.com/v1/calendar/${d.getFullYear()}/${d.getMonth()+1}?latitude=${city.lat}&longitude=${city.lon}&method=${methodForCity()}&iso8601=true&latitudeAdjustmentMethod=3`);const j=await r.json();if(j.code!==200)throw Error();$('monthly-loading').classList.add('hidden');$('monthly-head').innerHTML=`<th>Date</th>${prayerKeys.map(k=>`<th>${t(k)}</th>`).join('')}`;$('monthly-body').innerHTML=j.data.map(x=>`<tr><td>${x.date.gregorian.day}</td>${prayerKeys.map(k=>`<td>${x.timings[apiNames[k]]}</td>`).join('')}</tr>`).join('')}catch{$('monthly-loading').textContent=t('error')}}
function calculateQibla(lat,lon){const kaabaLat=21.422487,kaabaLon=39.826206,p1=lat*Math.PI/180,p2=kaabaLat*Math.PI/180,dl=(kaabaLon-lon)*Math.PI/180,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function showQibla(){if(!city)return;$('qibla-panel').classList.remove('hidden');qibla=calculateQibla(city.lat,city.lon);$('qibla-bearing').textContent=`${Math.round(qibla)}°`;rotateCompass(qibla)}
function rotateCompass(v){$('compass-arrow').style.transform=`rotate(${v}deg)`}
async function enableOrientation(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')return}window.addEventListener('deviceorientation',e=>{if(typeof e.alpha==='number')rotateCompass(qibla-e.alpha)});}catch{}}
$('city-search').addEventListener('input',searchCities);$('search-button').onclick=searchCities;$('location-button').onclick=async()=>{if(!navigator.geolocation)return $('status').textContent=t('error');navigator.geolocation.getCurrentPosition(async p=>loadCity(await reverseGeocode(p.coords.latitude,p.coords.longitude)),()=>$('status').textContent=t('error'))};$('today-tab').onclick=()=>{selectedDay='today';renderSelectedDay()};$('tomorrow-tab').onclick=()=>{selectedDay='tomorrow';renderSelectedDay()};$('monthly-button').onclick=monthly;$('qibla-button').onclick=showQibla;$('orientation-button').onclick=enableOrientation;$('language-button').onclick=()=>{$('language-screen').classList.remove('hidden');$('app').classList.add('hidden')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));$('year').textContent=new Date().getFullYear();renderLangs();if(lang){applyLang();$('language-screen').classList.add('hidden');$('app').classList.remove('hidden');if(city)loadCity(city)}
